---
- name: Deploy plugin
  hosts: host-win

  tasks:
  - name: Kill StreamDeck
    # need WMI perms Enable remote and Execute methods
    ansible.windows.win_shell: "Stop-Process -Name StreamDeck -Force"
    args:
      executable: powershell
    # If already dead, error can be ignored
    ignore_errors: true

  - name: Delete content & directory
    ansible.windows.win_file:
      state: absent
      path: "{{ hostvars[inventory_hostname].release_plugins_dir }}\\{{ hostvars[inventory_hostname].release_plugin_dir_name }}"

  - name: Delete content & directory
    ansible.windows.win_file:
      state: directory
      path: "{{ hostvars[inventory_hostname].release_plugins_dir }}\\{{ hostvars[inventory_hostname].release_plugin_dir_name }}"

  - name: Copy files to Stream Deck plugin dir
    ansible.windows.win_copy:
      remote_src: true
      src: "{{ hostvars[inventory_hostname].plugin_home }}\\release\\build\\"
      dest: "{{ hostvars[inventory_hostname].release_plugins_dir }}\\{{ hostvars[inventory_hostname].release_plugin_dir_name }}"

  # Start-Process will not work as it cannot open interactive executables remotelly
  # workaround:
  #   1. Requires RDP - https://serverfault.com/questions/690852/use-powershell-to-start-a-gui-program-on-a-remote-machine
  #   2. Use Scheduled Task - need WMI perms Enable remote and Execute methods
  - name: Start StreamDeck
    win_shell: |
      $User = "{{ hostvars[inventory_hostname].ansible_user }}";
      $StreamDeck = New-ScheduledTaskAction -Execute "{{ hostvars[inventory_hostname].streamdeck_exe_path }}";
      Unregister-ScheduledTask -TaskName "StreamDeck" -Confirm:$false
      Register-ScheduledTask -TaskName "StreamDeck" -User $User -Action $StreamDeck;
      Start-ScheduledTask -TaskName "StreamDeck"
    args:
      executable: powershell
