---
- name: Docker service
  hosts: host-win

  tasks:
    - name: "Docker '{{ service }}' service - action: '{{ action }}'"
      ansible.windows.win_shell: "docker compose {{ action }} {{ service }} {{ '-d' if action == 'up' else ''}}"
      args:
        chdir: "{{ hostvars[inventory_hostname].plugin_home }}/ci_cd"
      register: result
      when:
        - action in ['up', 'down', 'build']
        - service is defined
      failed_when: >
        (result is undefined) or
        (result.rc != 0)