name: ansible-cicd
version: "3.8"

services:
  ansible-ctl:
    image: ansible-controller
    profiles:
      - ansible
    build:
      context: ../
      dockerfile: ci_cd/containers/ansible_controller.dockerfile

    hostname: ansible-ctl
    command: "${PLAYBOOK}"
    volumes:
      - ../:/opt/plugin_home
      - ../ci_cd/playbooks/:/ansible/playbooks/
      - ../ci_cd/inventory/:/ansible/inventory/
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - defnet
    deploy:
      resources:
        reservations:
          cpus: "4.0"
          memory: 300M

  frontend-builder:
    profiles:
      - frontend
    image: frontend-builder-host
    build:
      context: ../
      dockerfile: ci_cd/containers/worker_frontend.dockerfile
    hostname: frontend-builder
    volumes:
      - ../:/opt/plugin_home
      - worker_frontend_npm:/home/ansible/.npm
    networks:
      - defnet
    deploy:
      resources:
        reservations:
          cpus: "4.0"
          memory: 400M

networks:
  defnet:

volumes:
  worker_frontend_npm:
